version: "3.9"

services:
  db:
    image: postgres:${POSTGRES_VERSION}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - .env.development

volumes:
  db:
    driver: local
