CREATE TABLE IF NOT EXISTS bookings (
  id SERIAL PRIMARY KEY,
  mail VARCHAR(255) NOT NULL,
  day DATE NOT NULL,
  hour VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
