CREATE TABLE IF NOT EXISTS bookings (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  surname VARCHAR(255) NOT NULL,
  booking_date VARCHAR(255) NOT NULL,
  -- created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  -- updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
