CREATE TABLE IF NOT EXISTS timetables (
  id SERIAL PRIMARY KEY,
  hour VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
